use anchor_lang::prelude::*;

pub mod instructions;
pub mod accounts;
pub mod events;
pub mod errors;
pub mod constants;

use instructions::*;

declare_id!("ReplaceWithYourProgramID");

#[program]
pub mod pokebattle {
    use super::*;

    pub fn initialize_user(ctx: Context<InitializeUser>) -> Result<()> {
        instructions::initialize_user::handler(ctx)
    }

    pub fn publish_card(
        ctx: Context<PublishCard>,
        name: String,
        metadata: String,
        rarity: String,
        element_type: String,
    ) -> Result<()> {
        instructions::publish_card::handler(ctx, name, metadata, rarity, element_type)
    }

    // HatchEgg: admin (backend) calls this to create CardInstance for a user.
    pub fn hatch_egg(
        ctx: Context<HatchEgg>,
        user_pubkey: Pubkey,
        card_id: u64,
        instance_id: u64, // generated by backend for determinism
        backend_payload: Vec<u8>, // for audit (optional)
    ) -> Result<()> {
        instructions::hatch_egg::handler(ctx, user_pubkey, card_id, instance_id, backend_payload)
    }

    pub fn start_battle(ctx: Context<StartBattle>, stake: u64) -> Result<()> {
        instructions::start_battle::handler(ctx, stake)
    }

    pub fn end_battle(ctx: Context<EndBattle>) -> Result<()> {
        instructions::end_battle::handler(ctx)
    }

    pub fn create_battle_record(
        ctx: Context<CreateBattleRecord>,
        winner: Option<Pubkey>,
        result_note: String,
    ) -> Result<()> {
        instructions::create_battle_record::handler(ctx, winner, result_note)
    }
}